dic = {
    "<2_hours": ["<2 horas", "<2 hours"],
    "between_2_3_hours": ["entre 2 e 3 horas", "between 2 and 3 hours"],
    ">3_hours": [">3 horas", ">3 hours"],
    "0_60_points": ["0 a 60 Pontos", "0 to 60 Points"],
    "60_120_points": ["60 a 120 Pontos", "60 to 120 Points"],
    "120_points": ["Mais de 120 Pontos", "More than 120 Points"],
    "30_days": ["Primeiros 30", "First 30"],
    "30_90_days": ["De 30 a 90", "From 30 to 90"],
    "90_days": ["Superior a 90", "Greater than 90"],
    "ACS_dyspnea": ["ACS dispneia", "ACS dyspnea"],
    "ACS_functional_status": ["ACS estado funcional", "ACS functional status"],
    "ACS_acute_renal_failure": ["ACS insuficiência renal aguda", "ACS acute renal failure"],
    "ACS_weight": ["ACS peso", "ACS weight"],
    "ACS_systemic_sepsis": ["ACS sépsis sistémica", "ACS systemic sepsis"],
    "ARISCAT_preoperative_anemia": ["ARISCAT anemia pré-operativa", "ARISCAT preoperative anemia"],
    "ARISCAT_surgery_duration": ["ARISCAT duração cirurgia", "ARISCAT surgery duration"],
    "ARISCAT_respiratory_infection": ["ARISCAT infeção respiratória último mês", "ARISCAT respiratory infection last month"],
    "ARISCAT_emergent_procedure": ["ARISCAT procedimento emergente", "ARISCAT emergent procedure"],
    "calculate": ["Calcular", "Result"],
    "clavien_dindo_scale": ["(Segundo a escala Clavien-Dindo)", "(According Clavien-Dindo scale)"],
    "complications": ["Complicações", "Complications"],
    "complications_i": ["Probabilidade de complicações de GRAU I", "Probability of GRADE I complications"],
    "complications_ii": ["Probabilidade de complicações de GRAU II", "Probability of GRADE II complications"],
    "complications_iii": ["Probabilidade de complicações de GRAU III", "Probability of GRADE III complications"],
    "complications_iv": ["Probabilidade de complicações de GRAU IV", "Probability of GRADE IV complications"],
    "current_patient": ["Paciente Atual", "Current Patient"],
    "days_after_surgery": ["Dias Após Cirurgia", "Days After Surgery"],
    "death_1_year": ["Óbito - 1 ano", "Death - 1 year"],
    "death_months": ["Óbito - Meses", "Death - months"],
    "death_30_days": ["Probabilidade de morte nos primeiros 30 dias", "Probability of death in the first 30 days"],
    "death_30_90_days": ["Probabilidade de morte entre o 30º e o 90º dia", "Probability of death between the 30th and 90th day"],
    "death_90_days": ["Probabilidade de morte após o 90º dia", "Probability of death after the 90th day"],
    "error_points": ["Erro (pontos)", "Error (points)"],
    "error_days": ["Erro (dias)", "Error (days)"],
    "high_probability_complications": ["ALTA probabilidade de complicações", "HIGH probability of complications"],
    "high_probability_death": ["ALTA probabilidade de morte no espaço de 1 ano", "HIGH probability of death within 1 year"],
    "home": ["Geral", "Home"],
    "hospitalization_1_day": ["Internamento até 1 dia", "Hospitalization up to 1 day"],
    "hospitalization_1_2_days": ["Internamento entre 1 a 2 dias", "Hospitalization between 1 to 2 days"],
    "hospitalization_2_days": ["Internamento superior a 2 dias", "Hospitalization longer than 2 days"],
    "hospitalization_7_days": ["Internamento até 7 dias", "Hospitalization up to 7 days"],
    "hospitalization_7_10_days": ["Internamento entre 7 a 10 dias", "Hospitalization between 7 to 10 days"],
    "hospitalization_10_20_days": ["Internamento entre 10 a 20 dias", "Hospitalization between 10 to 20 days"],
    "hospitalization_20_days": ["Internamento superior a 20 dias", "Hospitalization longer than 20 days"],
    "ipop_days": ["Dias no IPOP", "Days in IPOP"],
    "low_probability_complications": ["BAIXA probabilidade de complicações", "LOW probability of complications"],
    "low_probability_death": ["BAIXA probabilidade de morte no espaço de 1 ano", "LOW probability of death within 1 year"],
    "nas": ["Pontos NAS", "NAS Score"],
    "no": ["Não", "No"],
    "PP_peritoneal_contamination": ["PP contaminação peritoneal", "PP peritoneal contamination"],
    "PP_status_of_malignancy": ["PP estado da malignidade", "PP status of malignancy"],
    "PP_hemoglobin": ["PP hemoglobina", "PP hemoglobin"],
    "PP_leukocytes": ["PP leucócitos", "PP leukocytes"],
    "PP_procedures": ["PP nº procedimentos", "PP no. procedures"],
    "PP_arterial_pulse": ["PP pulsação arterial", "PP arterial pulse"],
    "PP_respiratory": ["PP respiratório", "PP respiratory"],
    "PP_sodium": ["PP sódio", "PP sodium"],
    "PP_urea": ["PP ureia", "PP urea"],
    "predicted_points": ["Pontos Previstos", "Predicted Points"],
    "predicted_days": ["Dias Previstos", "Predicted Days"],
    "prediction": ["Previsão: ", "Prediction: "],
    "probability": ["Probabilidiade", "Probability"],
    "result": ["Resultado: ", "Result: "],
    "severity": ["Severidade", "Severity"],
    "training_data": ["Dados de Treino", "Training Data"],
    "uci_days": ["Dias na UCI", "Days in UCI"],
    "yes": ["Sim", "Yes"],
    "none": ["Nenhum", "None"],
    "sirs": ["Síndrome de Resposta Inflamatória Sistémica (SIRS)", "Systemic Inflammatory Response Syndrome (SIRS)"],
    "sepsis": ["Sépsis", "Sepsis"],
    "septic_shock": ["Choque séptico", "Septic shock"],
    "one": ["Um", "One"],
    "two": ["Dois", "Two"],
    "three": ["Três ou mais", "Three or more"],
    "no_contamination": ["Sem contaminação", "No Contamination"],
    "minimal_contamination": ["Contaminação Mínima", "Minimal Contamination"],
    "local_pus": ["Pus Local", "Local Pus"],
    "free_contents": ["Conteúdo livre do intestino, pus ou sangue", "Free contents of the intestine, pus or blood"],
    "independent": ["Independente", "Independent"],
    "partially_dependent": ["Parcialmente dependente", "Partially dependent"],
    "fully_dependent": ["Totalmente dependente", "Fully dependent"],
    "no_dyspnea": ["Sem dispneia", "No dyspnea"],
    "mild_COAD": ["Dispneia no esforço, COAD leve", "Dyspnea on exertion, mild COAD"],
    "moderate_COAD": ["Dispneia limitada, COAD moderada", "Limited dyspnea, moderate COAD"],
    "dyspnea_rest": ["Dispeia em repouso, fibrose pulmonar/consolidação em raio-x", "Dyspnea at rest, pulmonary fibrosis/consolidation on x-ray"],
    "moderate_effort": ["Com esforço moderado", "With moderate effort"],
    "at_rest": ["Em repouso", "At rest"],
    "no_malignancy": ["Sem malignidade", "No malignancy"],
    "primary_malignancy": ["Apenas malignidade primária", "Primary malignancy only"],
    "nodal_metastases": ["Malignidade + metástases nodais", "Malignancy + nodal metastases"],
    "distant_metastasis": ["Malignidade + metástase distante", "Malignancy + distant metastasis"],
    "normal_ECG": ["ECG normal", "Normal ECG"],
    "ECG_AF": ["ECG AF, ritmo 60-90", "ECG AF, rhythm 60-90"],
    "abnormal_rhythm": ["Qualquer outro ritmo anormal,> 4/min ectópicos, ondas Q, alterações ST/T", "Any other abnormal rhythm,> 4/min ectopic, Q waves, ST/T changes"],
}
